book_price_list ={'100 year‐old Secret, The': 7,
 'Ajeemah and his Son': 6,
 'Among the Hidden': 8,
 'As Brave as You': 8,
 'Ashes': 17,
 'Awkward': 11,
 'Bad Island': 11,
 'Black Star, Bright Dawn': 7,
 'Boy Who Saved Baseball, The': 8,
 'Bubonic Panic: When Plague Invaded America': 19,
 'Candymakers, The': 10,
 'Chasing Secrets': 8,
 'Choosing Courage': 9,
 'Dateline: Troy': 9,
 'Deadly Flowers: A Ninja’s Tale': 18,
 'December Stillness': 9,
 'Dragon’s Keep': 8,
 'Eagle Strike': 9,
 'Echo': 20,
 "Ender's Shadow": 9,
 'Escape! The Story of the Great Houdini': 9,
 'Fever 1793': 9,
 'Girl Who Drank the Moon, The': 17,
 'Girl vs. Boy Band: The Right Track': 17,
 'Gregor the Overlander': 7,
 'House of Secrets': 8,
 'I will Always Write Back': 10,
 'Inside Out and Back Again': 8,
 'Knucklehead: Tall Tales & Mostly True Stories...': 13,
 'Leaving Protection': 9,
 'Locomotion': 9,
 'Magnus Chase and the Gods of Asgard, Book 2: Hammer of Thor': 20,
 'Notes From a Midnight Driver': 10,
 'Notorious Benedict Arnold': 10,
 'Outcasts of 19 Schuyler Place, The': 8,
 'Phineas Gage: A Gruesome but True Story about Brain Science': 10,
 'Ruins of Gorlan, The': 9,
 'Sasquatch in the Paint': 8,
 'Say Goodnight Gracie': 9,
 'Slacker': 7,
 'So B. It': 7,
 'Soar': 8,
 'Splendors and Glooms': 8,
 'Stella by Starlight': 8,
 'Surviving the Applewhites': 7,
 'The Boys Who Challenged Hitler: Knud Pedersen and the Churchill Club': 20,
 'The One Safe Place': 7,
 'The Seventh Most Important Thing': 8,
 'Theodore Boone: Kid Lawyer': 9,
 'Titanic: Voices from the Disaster': 8,
 'Virals': 10,
 'Wolf Hollow': 17,
 'Wonder': 17,
 'Yellow Star': 10}